# -*- coding: utf-8 -*-
################################################################################
## Form generated from reading UI file 'LogIn.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################
from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QWidget)

class Ui_LogInWindow(object):
    def setupUi(self, LogInWindow):
        if not LogInWindow.objectName():
            LogInWindow.setObjectName(u"LogInWindow")
        LogInWindow.resize(1080, 800)
        LogInWindow.setMinimumSize(QSize(1080, 800))
        LogInWindow.setMaximumSize(QSize(1080, 800))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        LogInWindow.setPalette(palette)
        font = QFont()
        font.setFamilies([u"Tahoma"])
        LogInWindow.setFont(font)
        LogInWindow.setMouseTracking(False)
        LogInWindow.setAutoFillBackground(False)
        LogInWindow.setStyleSheet(u"background-color:rgb(255, 255, 255);")
        self.centralwidget = QWidget(LogInWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.badge_number_input = QLineEdit(self.centralwidget)
        self.badge_number_input.setObjectName(u"badge_number_input")
        self.badge_number_input.setGeometry(QRect(290, 430, 540, 60))
        self.badge_number_input.setMinimumSize(QSize(500, 60))
        self.badge_number_input.setMaximumSize(QSize(540, 60))
        font1 = QFont()
        font1.setFamilies([u"Tahoma"])
        font1.setBold(False)
        font1.setItalic(False)
        font1.setUnderline(False)
        font1.setStrikeOut(False)
        self.badge_number_input.setFont(font1)
        self.badge_number_input.setStyleSheet(u"background-color: rgb(245, 244, 246); \n"
"color: black; \n"
"font-size: 30px;\n"
"border: 2px solid black;")
        self.badge_number_input.setMaxLength(15)
        self.badge_number_input.setFrame(True)
        self.badge_number_input.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.log_in_button = QPushButton(self.centralwidget)
        self.log_in_button.setObjectName(u"log_in_button")
        self.log_in_button.setGeometry(QRect(390, 520, 300, 58))
        self.log_in_button.setMinimumSize(QSize(300, 58))
        self.log_in_button.setMaximumSize(QSize(300, 58))
        font2 = QFont()
        font2.setFamilies([u"Tahoma"])
        font2.setWeight(QFont.DemiBold)
        font2.setItalic(False)
        font2.setUnderline(False)
        font2.setStrikeOut(False)
        font2.setKerning(True)
        font2.setStyleStrategy(QFont.PreferAntialias)
        font2.setHintingPreference(QFont.PreferDefaultHinting)
        self.log_in_button.setFont(font2)
        self.log_in_button.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.log_in_button.setMouseTracking(True)
        self.log_in_button.setStyleSheet(u"border: 2px solid #555;\n"
"border-radius: 14px;  \n"
"background-color: rgb(0, 78, 152); \n"
"color: white; \n"
"letter-spacing: 0.6px;\n"
"font-size: 29px;\n"
"")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(485, 40, 120, 120))
        self.label.setMinimumSize(QSize(120, 120))
        self.label.setMaximumSize(QSize(120, 120))
        font3 = QFont()
        font3.setFamilies([u"Tahoma"])
        font3.setKerning(True)
        self.label.setFont(font3)
        self.label.setPixmap(QPixmap(u"../IMGs/subaroooo_logo.png"))
        self.label.setScaledContents(True)
        self.badge_label_3 = QLabel(self.centralwidget)
        self.badge_label_3.setObjectName(u"badge_label_3")
        self.badge_label_3.setGeometry(QRect(340, 760, 400, 40))
        self.badge_label_3.setMinimumSize(QSize(400, 40))
        self.badge_label_3.setMaximumSize(QSize(400, 90))
        palette1 = QPalette()
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush)
        brush2 = QBrush(QColor(0, 0, 0, 128))
        brush2.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush2)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush2)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush2)
#endif
        self.badge_label_3.setPalette(palette1)
        font4 = QFont()
        font4.setFamilies([u"Tahoma"])
        font4.setWeight(QFont.Thin)
        font4.setItalic(False)
        font4.setUnderline(False)
        font4.setStrikeOut(False)
        self.badge_label_3.setFont(font4)
        self.badge_label_3.setStyleSheet(u"font-size: 12px;\n"
"color: Black; \n"
"letter-spacing: -0.5px;")
        self.badge_label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(440, 680, 200, 90))
        self.label_2.setMinimumSize(QSize(200, 90))
        self.label_2.setMaximumSize(QSize(200, 90))
        font5 = QFont()
        font5.setKerning(True)
        self.label_2.setFont(font5)
        self.label_2.setPixmap(QPixmap(u"../IMGs/subbaroo_long_name.jpg"))
        self.label_2.setScaledContents(True)
        self.badge_label_2 = QLabel(self.centralwidget)
        self.badge_label_2.setObjectName(u"badge_label_2")
        self.badge_label_2.setGeometry(QRect(440, 180, 200, 100))
        self.badge_label_2.setMinimumSize(QSize(200, 100))
        self.badge_label_2.setMaximumSize(QSize(200, 100))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush2)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush2)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush2)
#endif
        self.badge_label_2.setPalette(palette2)
        font6 = QFont()
        font6.setFamilies([u"Tahoma"])
        font6.setWeight(QFont.Black)
        font6.setItalic(False)
        font6.setUnderline(False)
        font6.setStrikeOut(False)
        self.badge_label_2.setFont(font6)
        self.badge_label_2.setStyleSheet(u"font-size: 38px;\n"
"color: Black; \n"
"letter-spacing: 0.6px;\n"
"")
        self.badge_label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.badge_label_4 = QLabel(self.centralwidget)
        self.badge_label_4.setObjectName(u"badge_label_4")
        self.badge_label_4.setGeometry(QRect(240, 310, 600, 100))
        self.badge_label_4.setMinimumSize(QSize(600, 100))
        self.badge_label_4.setMaximumSize(QSize(600, 100))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush2)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush2)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush2)
#endif
        self.badge_label_4.setPalette(palette3)
        font7 = QFont()
        font7.setFamilies([u"Tahoma"])
        font7.setWeight(QFont.DemiBold)
        font7.setItalic(False)
        font7.setUnderline(False)
        font7.setStrikeOut(False)
        self.badge_label_4.setFont(font7)
        self.badge_label_4.setStyleSheet(u"font-size: 34px;\n"
"color: Black; \n"
"")
        self.badge_label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(260, 430, 60, 60))
        self.label_3.setMinimumSize(QSize(60, 60))
        self.label_3.setMaximumSize(QSize(60, 60))
        self.label_3.setFont(font3)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet(u"border: 2px solid black;")
        self.label_3.setPixmap(QPixmap(u"../IMGs/account_logo.png"))
        self.label_3.setScaledContents(True)
        LogInWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LogInWindow)

        QMetaObject.connectSlotsByName(LogInWindow)
    # setupUi

    def retranslateUi(self, LogInWindow):
        LogInWindow.setWindowTitle(QCoreApplication.translate("LogInWindow", u"Log In", None))
        self.badge_number_input.setText("")
        self.log_in_button.setText(QCoreApplication.translate("LogInWindow", u"Login", None))
        self.label.setText("")
        self.badge_label_3.setText(QCoreApplication.translate("LogInWindow", u"COPYRIGHT \u00a9 2024 ALL RIGHTS RESERVED", None))
        self.label_2.setText("")
        self.badge_label_2.setText(QCoreApplication.translate("LogInWindow", u"Welcome!", None))
        self.badge_label_4.setText(QCoreApplication.translate("LogInWindow", u"Enter Badge Number to Continue", None))
        self.label_3.setText("")
    # retranslateUi

